### ISSUE TITLE
How to best update/upgrade to newest version of Qiime 2

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/docs.qiime2.org#18]
Edit:

## The easiest way to update is to just install the newest version in a new conda environment by following the normal install instructions. 

The install instructions are [in the documentation](https://docs.qiime2.org).  

---

Original post: 

We used to have [official docs](https://docs.qiime2.org/2017.7/upgrade/#updating-qiime-2-core-2017-7) for updating / upgrading to the newest version of Qiime.

This could be helpful on the [forums](https://forum.qiime2.org/t/updating-qiime2-2018-2-to-2018-4/4017), and could be a simple link on the Qiime 2 conda [install page](https://docs.qiime2.org/2018.4/install/).

**Comment by ebolyen** [comment]
We learned that those documents confused people more than anything, as they would often get the relationship backwards. Additionally the "upgrading" docs basically repeated the install docs.

Perhaps it is worth having an Upgrading page *only*  that just states to install a new environment (or VM) and indicating that you can either keep the old environment or delete it (and how).

**Comment by thermokarst** [comment]
Perhaps this could be a `.. note::` in the native install doc?

**Comment by colinbrislawn** [comment]
Yes, offering a single clear description is probably better than two pages. I'm glad you discovered this.

I like the idea of a note about "to upgrade, you just install again" and how to remove an older conda environments. Could we put that at the bottom of the [Native install page](https://github.com/qiime2/docs.qiime2.org/blob/gh-pages/2017.4/_sources/install/native.txt)?

**Comment by thermokarst** [comment]
Sorry @colinbrislawn, didn't notice that this issue was opened on the "wrong" repo --- we don't use this repo for code management, rather, it just serves as a place to serve the docs HTML once rendered (we use GitHub Pages for that). The actual docs repo is over at https://github.com/qiime2/docs. Sorry!
